### PR TITLE
Bring level and leveldown up-to-date

### PR DESCRIPTION
**Pull request by christianbundy**
Please see: https://github.com/ssbc/secure-scuttlebutt/pull/204#issuecomment-386372685

I've also de-duped the `leveldown` dependency from `dependencies` to follow the intention behind https://github.com/Level/level-test/commit/60b3fc39ea879e332dcfe05d7f5280221eda2f4a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2. Please let me know if this was misguided. Thanks!

### CODE REVIEW

**Comment by myf** [comment]
you are always few minutes ahead of me! oh well

**Comment by vweevers** [comment]
Sadly this is not enough, due to `levelup` API changes. The breakage is not covered by tests here. And I think making `leveldown` an optional dependency is moot if we also depend on `level` (which in turn depends on `leveldown`).

💡 We can replace `level` with `level-packager` and ditch the `levelup` dependency. Lastly, we should also update `memdown`. Then it's:

```js
var packager = require('level-packager')
var memdown = require('memdown')
var leveldown = require('leveldown') // Imagine a try/catch wrapper here

function wrap(factory) {
  return function (loc, opts, cb) {
    // Imagine cleanup and tmp dir creation here
    // ..

    return factory(loc, opts, cb)
  }
}

module.exports = function (opts) {
  opts = opts || {}
  return opts.mem ? packager(memdown) : wrap(packager(leveldown))
}
```

@ralphtheninja WDYT?
@christianbundy I can whip up a PR if you like

**Comment by ralphtheninja** [comment]
> @ralphtheninja WDYT?

Go nuts!

**Comment by christianbundy** [comment]
@ralphtheninja Done! Is there somewhere I can learn more about when `package-lock.json` should be manually removed?

@vweevers Go nuts! You can PR if you'd like, but I'll add you as a contributor to my fork if you'd just like to push to this branch. :+1:

**Comment by vweevers** [comment]
Re: package-lock: see https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514.

I'll do a fresh PR against `level/level-test`, maybe I can add some tests before updating and refactoring.

**Comment by vweevers** [comment]
#60

**Pull request closed without merging**
